package main

// KnowledgeBase is a diverse set of text snippets for testing semantic correlation
var KnowledgeBase = []string{
	"The Loom engine uses a 3D volumetric coordinate system (Depth, Row, Col) for tensor dispatch.",
	"WebGPU allows for high-performance neural network inference and training directly in the browser.",
	"Bit-perfect reproducibility is the core philosophy of the Poly engine, ensuring 0% divergence across platforms.",
	"The M-POLY-VTD architecture supports 21 different numerical types, from FP64 down to 1-bit Binary.",
	"Tiling optimization in Poly caches tensors in shared memory to avoid redundant global memory reads.",
	"A black hole is a region of spacetime where gravity is so strong that nothing, including light, can escape.",
	"The James Webb Space Telescope is the most powerful space telescope ever built, designed to see the first stars.",
	"Mars is often called the Red Planet because of the iron oxide (rust) on its surface.",
	"Photosynthesis is the process by which green plants use sunlight to synthesize nutrients from carbon dioxide and water.",
	"DNA, or deoxyribonucleic acid, is the molecule that carries genetic instructions for all living organisms.",
	"The human heart beats approximately 100,000 times a day, pumping blood throughout the body.",
	"To bake a chocolate cake, you need flour, sugar, cocoa powder, eggs, milk, and vegetable oil.",
	"Sourdough bread is made by the fermentation of dough using naturally occurring lactobacilli and yeast.",
	"The Roman Empire reached its greatest territorial extent under the Emperor Trajan in 117 AD.",
	"The Renaissance was a fervent period of European cultural, artistic, political, and economic rebirth following the Middle Ages.",
	"Quantum mechanics is a fundamental theory in physics that describes the physical properties of nature at the scale of atoms.",
	"The speed of light in a vacuum is approximately 299,792,458 meters per second.",
	"In chemistry, an atom is the smallest unit of ordinary matter that forms a chemical element.",
	"A volcano is a rupture in the crust of a planetary-mass object, such as Earth, that allows hot lava to escape.",
	"The Great Barrier Reef is the world's largest coral reef system, located in the Coral Sea off the coast of Australia.",
	"Artificial Intelligence is the simulation of human intelligence processes by machines, especially computer systems.",
	"Loom's TargetProp is an alternative to backpropagation designed for zero-backprop training on edge devices.",
	"The SwiGLU activation function is a variant of the Gated Linear Unit used in many modern LLM architectures.",
	"RMSNorm is a simplification of LayerNorm that improves computational efficiency in large-scale transformers.",
	"K-Means clustering is an unsupervised learning algorithm used to group data points into K distinct clusters.",
	"Semantic search uses embeddings to find information based on meaning rather than just keyword matching.",
	"A GPU (Graphics Processing Unit) is a specialized electronic circuit designed to rapidly manipulate and alter memory.",
	"The Turing architecture by NVIDIA introduced RT Cores and Tensor Cores for ray tracing and AI acceleration.",
	"Mamba is a state-space model architecture that aims to provide linear scaling for long-sequence tasks.",
	"Causal convolution ensures that the output at time t only depends on inputs from time t and earlier.",
}
